name: PROXY Updater

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * */1 *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - run: curl -s -L https://raw.githubusercontent.com/gbeag/DE-ArenaRegen/master/update.py -o update.py
    - run: python update.py
    - name: Commit files
      run: |
        git config --local user.email ${{ secrets.GIT_EMAIL }}
        git config --local user.name ${{ secrets.GIT_NAME }}
        git add file.txt
        git commit -am "출첵"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
      env:
        CI: true
